./wumpusrun MAPS/easy1.txt 1 1
./wumpusrun MAPS/easy2.txt 1 1
./wumpusrun MAPS/easy3.txt 1 1
./wumpusrun MAPS/easy4.txt 2 2
./wumpusrun MAPS/easy5.txt 2 2
./wumpusrun MAPS/medium1.txt 3 4
./wumpusrun MAPS/medium2.txt 5 2
./wumpusrun MAPS/medium3.txt 4 2
./wumpusrun MAPS/medium4.txt 1 1
./wumpusrun MAPS/medium5.txt 1 2
./wumpusrun MAPS/hard1.txt 1 2
./wumpusrun MAPS/hard2.txt 3 2
./wumpusrun MAPS/hard3.txt 7 7
./wumpusrun MAPS/hard4.txt 3 1
./wumpusrun MAPS/hard5.txt 3 1
./wumpusrun MAPS/vhard1.txt 8 1
./wumpusrun MAPS/vhard2.txt 1 2
./wumpusrun MAPS/vhard3.txt 10 9
